name: Swift Statistics Package

on:
  push:
    branches: [ master, dockerAction ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Test
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "Cub40i" --password-stdin
        docker image build -t yellowcub/Statistics

